package com.davidtrott.mdtracker.model;
// Generated May 11, 2010 12:22:15 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DependencyId generated by hbm2java
 */
@Embeddable
public class DependencyId implements java.io.Serializable {

	private int moduleVersionId;
	private int moduleRangeId;

	public DependencyId() {
	}

	public DependencyId(int moduleVersionId, int moduleRangeId) {
		this.moduleVersionId = moduleVersionId;
		this.moduleRangeId = moduleRangeId;
	}

	@Column(name = "module_version_id", nullable = false)
	public int getModuleVersionId() {
		return this.moduleVersionId;
	}

	public void setModuleVersionId(int moduleVersionId) {
		this.moduleVersionId = moduleVersionId;
	}

	@Column(name = "module_range_id", nullable = false)
	public int getModuleRangeId() {
		return this.moduleRangeId;
	}

	public void setModuleRangeId(int moduleRangeId) {
		this.moduleRangeId = moduleRangeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DependencyId))
			return false;
		DependencyId castOther = (DependencyId) other;

		return (this.getModuleVersionId() == castOther.getModuleVersionId())
				&& (this.getModuleRangeId() == castOther.getModuleRangeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModuleVersionId();
		result = 37 * result + this.getModuleRangeId();
		return result;
	}

}
