package com.davidtrott.mdtracker.model;
// Generated May 11, 2010 12:22:15 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Dependency generated by hbm2java
 */
@Entity
@Table(name = "dependency")
public class Dependency implements java.io.Serializable {

	private DependencyId id;
	private int version;
	private ModuleVersion moduleVersion;
	private ModuleRange moduleRange;

	public Dependency() {
	}

	public Dependency(DependencyId id, ModuleVersion moduleVersion,
			ModuleRange moduleRange) {
		this.id = id;
		this.moduleVersion = moduleVersion;
		this.moduleRange = moduleRange;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "moduleVersionId", column = @Column(name = "module_version_id", nullable = false)),
			@AttributeOverride(name = "moduleRangeId", column = @Column(name = "module_range_id", nullable = false))})
	@NotNull
	public DependencyId getId() {
		return this.id;
	}

	public void setId(DependencyId id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_version_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public ModuleVersion getModuleVersion() {
		return this.moduleVersion;
	}

	public void setModuleVersion(ModuleVersion moduleVersion) {
		this.moduleVersion = moduleVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_range_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public ModuleRange getModuleRange() {
		return this.moduleRange;
	}

	public void setModuleRange(ModuleRange moduleRange) {
		this.moduleRange = moduleRange;
	}

}
