package com.davidtrott.mdtracker.model;
// Generated May 11, 2010 12:22:15 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.*;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", uniqueConstraints = @UniqueConstraint(columnNames = {
		"group_id", "artifact_id"}))
public class Module implements java.io.Serializable {

	private int moduleId;
	private int version;
	private String groupId;
	private String artifactId;
	private Set<ModuleRange> moduleRanges = new HashSet<ModuleRange>(0);
	private Set<ModuleVersion> moduleVersions = new HashSet<ModuleVersion>(0);

	public Module() {
	}

	public Module(int moduleId, String groupId, String artifactId) {
		this.moduleId = moduleId;
		this.groupId = groupId;
		this.artifactId = artifactId;
	}
	public Module(int moduleId, String groupId, String artifactId,
			Set<ModuleRange> moduleRanges, Set<ModuleVersion> moduleVersions) {
		this.moduleId = moduleId;
		this.groupId = groupId;
		this.artifactId = artifactId;
		this.moduleRanges = moduleRanges;
		this.moduleVersions = moduleVersions;
	}

	@Id
	@GeneratedValue
	@Column(name = "module_id", unique = true, nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "group_id", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "artifact_id", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getArtifactId() {
		return this.artifactId;
	}

	public void setArtifactId(String artifactId) {
		this.artifactId = artifactId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<ModuleRange> getModuleRanges() {
		return this.moduleRanges;
	}

	public void setModuleRanges(Set<ModuleRange> moduleRanges) {
		this.moduleRanges = moduleRanges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<ModuleVersion> getModuleVersions() {
		return this.moduleVersions;
	}

	public void setModuleVersions(Set<ModuleVersion> moduleVersions) {
		this.moduleVersions = moduleVersions;
	}

}
